#!/bin/bash

function echo_usage() {
    echo "Usage: stats {-rows|-cols} [input]" 1>&2
}

function echo_badfile() {
    echo "./stats: cannot read $1" 1>&2
}

function echo_nodata() {
    echo "No data in input" 1>&2
}

# Checking to see if inputs are valid
# Echoes usage and exits if invalid

if [ $# -ne 1 ] && [ $# -ne 2 ];
then
    echo_usage
    exit 1
fi

if [[ $1 != -r* ]] && [[ $1 != -c* ]];
then
    echo_usage
    exit 1
fi

if [ $# -gt 2 ];
then
    echo_usage
    exit 1
fi

if [ $# -eq 2 ] && [ ! -f "$2" ];
then
    echo_badfile $2
    exit 1
fi

# -row option
if [[ $1 == -r* ]];
then
    tempfile="tempfile$$"
    read firstRow < "${2:-/dev/stdin}"
    # Exits if there are no inputs
    if [[ $firstRow == "" ]]
    then
        echo_nodata
        exit 0
    fi

    echo Average Median
    while read curRow
    do
        # Initialize accumulators to 0
        sum=0
        count=0

        # Clear the contents of temporary file before next row
        > $tempfile

        for num in $curRow
        do
            sum=`expr $sum + $num`
            count=`expr $count + 1`
            echo $num >> $tempfile
        done
        sort -g $tempfile -o $tempfile

        # Prints the average
        printf "%b\t" "$(( ($sum + ($count / 2)) / $count ))"

        # Prints the median
        head -$(( ($count + 2) / 2 )) $tempfile | tail -1

        # Checks if data should be read from file or stdin
        # https://stackoverflow.com/questions/6980090/how-to-read-from-file-or-stdin-in-bash
    done < "${2:-/dev/stdin}"
    rm -f $tempfile
fi

# -col version
if [[ $1 == -c* ]];
then
    read firstrow < "${2:-/dev/stdin}"
    if [[ $firstrow == "" ]]
    then
        echo_nodata
        exit 0
    fi

    average=""
    median=""
    curcol=1
    tempfile="tempfile$$"
    for cols in $firstrow
    do
        firstcol=`cut -f$curcol ${2:-/dev/stdin}`
        sum=0
        count=0
        > $tempfile

        for num in $firstcol
        do
            sum=`expr $sum + $num`
            count=`expr $count + 1`
            echo $num >> $tempfile
        done
        sort -g $tempfile -o $tempfile

        if [ $curcol -eq 1 ];
        then
            average="$(( ($sum + ($count / 2)) / $count ))"
            median="`head -$(( ($count + 2) / 2 )) $tempfile | tail -1`"
        else
            average="$average"$'\t'"$(( ($sum + ($count / 2)) / $count ))"
            median="$median"$'\t'"`head -$(( ($count + 2) / 2 )) $tempfile | tail -1`"
        fi
        curcol=`expr $curcol + 1`
    done
    echo Averages:
    echo $average
    echo Medians:
    echo $median
    rm -f $tempfile
fi
